### PR TITLE
Update style to look less obstrusive in sidebars

### PR DESCRIPTION
**Pull request by bkimminich**

### CODE REVIEW

**Comment by mikemccamon** [comment]
I don't have a local environment to see how this looks but I'm generally cool with doing some fixing of project classification formatting. We've been experimenting/iterating to a destination.

**Comment by bkimminich** [comment]
You can see it here: https://owasp.org/www-project-juice-shop/

**Comment by bkimminich** [comment]
Long term this would of course be nice to be generated automatically from metadata, giving visual consistency across projects and a single place to make changes in the future.

**Comment by mikemccamon** [comment]
Exactly!

====================
Mike McCamon
Executive Director, OWASP
913.940.2737
Sent while mobile so please excuse typos

**Pull request merged**
